// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4Fn5gSyoDtvvZpYZq1rz_joycMGRJaQ',
    appId: '1:426332356943:web:da6d2a9cb2090334e0853a',
    messagingSenderId: '426332356943',
    projectId: 'expensetrackerapp-aead3',
    authDomain: 'expensetrackerapp-aead3.firebaseapp.com',
    storageBucket: 'expensetrackerapp-aead3.appspot.com',
    measurementId: 'G-KSJH7PPCBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLSXgGPPwfGSKazj5_4UEPlgL_qMSUJSU',
    appId: '1:426332356943:android:68737dae101be2b4e0853a',
    messagingSenderId: '426332356943',
    projectId: 'expensetrackerapp-aead3',
    storageBucket: 'expensetrackerapp-aead3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xRVCpMQoForkgPxQHW2ITWCblila6gc',
    appId: '1:426332356943:ios:ce20c1cfb15ca420e0853a',
    messagingSenderId: '426332356943',
    projectId: 'expensetrackerapp-aead3',
    storageBucket: 'expensetrackerapp-aead3.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5xRVCpMQoForkgPxQHW2ITWCblila6gc',
    appId: '1:426332356943:ios:ce20c1cfb15ca420e0853a',
    messagingSenderId: '426332356943',
    projectId: 'expensetrackerapp-aead3',
    storageBucket: 'expensetrackerapp-aead3.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx4Fn5gSyoDtvvZpYZq1rz_joycMGRJaQ',
    appId: '1:426332356943:web:f1176841ce5cb4f1e0853a',
    messagingSenderId: '426332356943',
    projectId: 'expensetrackerapp-aead3',
    authDomain: 'expensetrackerapp-aead3.firebaseapp.com',
    storageBucket: 'expensetrackerapp-aead3.appspot.com',
    measurementId: 'G-0SL8HMC95E',
  );
}
